export const data = {
    persons: [
        {
            photo: '',
            name: 'Андрей',
            message: 'Изображение',
            you: true,
            isUnread: true,
            countUnreadMessage: 2,
            time: '10:49',
            dayOfWeek: '',
            date: '',
            selected: false,
        },
        {
            photo: '',
            name: 'Киноклуб',
            message: 'стикер',
            you: false,
            isUnread: false,
            countUnreadMessage: '',
            time: '12:00',
            dayOfWeek: '',
            date: '',
            selected: false,
        },
        {
            photo: '',
            name: 'Матрос',
            message: 'Друзья, у меня для вас особенный выпуск новостей!...',
            you: false,
            isUnread: true,
            countUnreadMessage: 5,
            time: '15:12',
            dayOfWeek: '',
            date: '',
            selected: false,
        },
        {
            photo: '',
            name: 'Вадим',
            message: 'Клёво!',
            you: true,
            isUnread: false,
            countUnreadMessage: '',
            time: '',
            dayOfWeek: 'Пт',
            date: '',
            selected: true,
        },
        {
            photo: '',
            name: 'Руслан',
            message: 'И Human Interface Guidelines и Material Design рекомендуют...',
            you: false,
            isUnread: true,
            countUnreadMessage: 8,
            time: '',
            dayOfWeek: 'Ср',
            date: '',
            selected: false,
        },
        {
            photo: '',
            name: '+7 (111) ...',
            message: 'Миллионы россиян ежедневно проводят десятки часов свое...',
            you: false,
            isUnread: false,
            countUnreadMessage: '',
            time: '',
            dayOfWeek: 'Вт',
            date: '',
            selected: false,
        },
        {
            photo: '',
            name: 'Стас',
            message: 'В 2008 году художник Jon Rafman начал собирать...',
            you: false,
            isUnread: false,
            countUnreadMessage: '',
            time: '',
            dayOfWeek: 'Пн',
            date: '',
            selected: false,
        },
        {
            photo: '',
            name: 'Daniel',
            message: 'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
            you: false,
            isUnread: false,
            countUnreadMessage: '',
            time: '',
            dayOfWeek: '',
            date: '11 Мая 2022',
            selected: false,
        },
        {
            photo: '',
            name: 'Maxim Shevtsov',
            message: 'Можно или сегодня или завтра вечером.',
            you: false,
            isUnread: false,
            countUnreadMessage: '',
            time: '',
            dayOfWeek: '',
            date: '2 Jul 2020',
            selected: false,
        },
        {
            photo: '',
            name: 'Maxim Shevtsov',
            message: 'Можно или сегодня или завтра вечером.',
            you: false,
            isUnread: false,
            countUnreadMessage: '',
            time: '',
            dayOfWeek: '',
            date: '2 Jul 2020',
            selected: false,
        },
        {
            photo: '',
            name: 'Maxim Shevtsov',
            message: 'Можно или сегодня или завтра вечером.',
            you: false,
            isUnread: false,
            countUnreadMessage: '',
            time: '',
            dayOfWeek: '',
            date: '2 Jul 2020',
            selected: false,
        },
        {
            photo: '',
            name: 'Maxim Shevtsov',
            message: 'Можно или сегодня или завтра вечером.',
            you: false,
            isUnread: false,
            countUnreadMessage: '',
            time: '',
            dayOfWeek: '',
            date: '2 Jul 2020',
            selected: false,
        },
        {
            photo: '',
            name: 'Maxim Shevtsov',
            message: 'Можно или сегодня или завтра вечером.',
            you: false,
            isUnread: false,
            countUnreadMessage: '',
            time: '',
            dayOfWeek: '',
            date: '2 Jul 2020',
            selected: false,
        },
        {
            photo: '',
            name: 'Maxim Shevtsov',
            message: 'Можно или сегодня или завтра вечером.',
            you: false,
            isUnread: true,
            countUnreadMessage: 2,
            time: '',
            dayOfWeek: '',
            date: '2 Jul 2020',
            selected: false,
        },
    ],
};
